Try stretched grids
CliMA/TurbulenceConvection.jl pull request #672
Opened 2021-12-22 02:36 UTC by charleskawczynski

I think this is all that's needed to actually use stretched grids now. For now this PR just uses the `CC.Meshes.ExponentialStretching(7.5e3)`, but there's a generalized stretching formulation in the design docs that we can use, as @tapios pointed out. I didn't see it implemented in ClimaCore, but it should be easy to implement and this should be the only line that's required to change.

2021-12-22 22:37 UTC, szy21 commented
Is the generalized stretching function you need this one: https://github.com/CliMA/ClimaCore.jl/blob/8725010c313222d512d06a576cca8f7fa5e27f01/src/Meshes/interval.jl#L100? If so we can just change this line after the PR is merged

2021-12-23 17:24 UTC, trontrytel commented
Not sure why buildkite CI is marked all green. The results for TRMM look different. For example meant temperature and horizontal velocities are off near the top boundary of the domain

2021-12-23 17:28 UTC, yairchn commented
> Not sure why buildkite CI is marked all green. The results for TRMM look different. For example meant temperature and horizontal velocities are off near the top boundary of the domain

I extended the domain above what it was and so you see theta profile that more in line with PYCLES. I added a slight increase in temperature at the top to have a strong tropopause in case updrafts develop too high, so they don't hit the top boundary

2021-12-23 17:29 UTC, yairchn commented
The tables have been updated, so they do not reflect the changes in the results. Are the convection changes substantial to you? or only the mean profiles?

2021-12-23 17:32 UTC, trontrytel commented
> The tables have been updated, so they do not reflect the changes in the results. Are the convection changes substantial to you? or only the mean profiles?

Hard to compare the contours if the domain is changed. Maybe we could extend the domain in one PR and then add the streching in another? This way we will be more certain that it does not affect the simulation negatively?

2021-12-23 18:44 UTC, yairchn commented
> the contours if the domain is changed. Maybe we could extend the domain in one PR and then add the streching in another? This way we will be more certain that it does not affect the simulation negatively?

but the profiles are aligned so you can see there the perspective of how high convection developed and the values associated with it

2021-12-23 18:57 UTC, trontrytel commented
> > the contours if the domain is changed. Maybe we could extend the domain in one PR and then add the streching in another? This way we will be more certain that it does not affect the simulation negatively?
> 
> but the profiles are aligned so you can see there the perspective of how high convection developed and the values associated with it

Looking just at the profiles then: I can spot that the variance is increasing in some cases, for example ARM, TRMM and Rico.

2021-12-23 21:33 UTC, yairchn commented
> > > the contours if the domain is changed. Maybe we could extend the domain in one PR and then add the streching in another? This way we will be more certain that it does not affect the simulation negatively?
> > 
> > 
> > but the profiles are aligned so you can see there the perspective of how high convection developed and the values associated with it
> 
> Looking just at the profiles then: I can spot that the variance is increasing in some cases, for example ARM, TRMM and Rico.

True, but are these increases a problem? do you think this change should not be merged? Variances are noisy anyways.

2021-12-23 21:34 UTC, yairchn approved these changes

2021-12-24 08:35 UTC, trontrytel commented
> > Looking just at the profiles then: I can spot that the variance is increasing in some cases, for example ARM, TRMM and Rico.
> 
> True, but are these increases a problem? do you think this change should not be merged? Variances are noisy anyways.

For Rico the difference is small and looks like noise. For TRMM I'm not sure if the change comes from stretching or the change of profiles you made. For ARM I'm just confused because I would think that the simulation should not have been changed at all? Looks good otherwise.

Did you guys test what is the effect of using the stretched grid on the simulation quality, for example by making the stretching more and more coarse? Or in other words, how did you chose the default value that is there right now?

Also, would it be possible to have it switch on/off as a namelist argument? In case we need it for debugging later?

2022-01-08 04:32 UTC, yairchn commented
I think this PR is ready now @trontrytel

2022-01-09 18:00 UTC, ilopezgp requested changes
I see that the exponential stretching would be hardcoded in this PR. I strongly prefer this to be optional, as @trontrytel suggested. Hardcoding the value of stretching is also not great.

2022-01-09 18:00 UTC, ilopezgp commented on driver/generate_namelist.jl
> +    namelist["grid"]["dz"] = 210
Why are the `dz` values changed?

2022-01-10 00:38 UTC, yairchn commented on driver/generate_namelist.jl
> +    namelist["grid"]["dz"] = 210
Sorry I meant to increase the domain height using 'nz' not 'dz'. I fixed the mistake now. Basically since the addition of snow the domain height was "tight" for the convection and the slight changes in grid stretching caused convection to hit the top and the model breaks (instability is detected).

2022-01-11 19:10 UTC, charleskawczynski commented on src/Grid.jl
> -    findfirst_center
This should not be commented out... @yairchn

2022-01-12 02:32 UTC, ilopezgp commented on driver/generate_namelist.jl
> +    namelist["grid"]["dz"] = 60.0
How should I think about `dz` when the grid is stretched? Is it the minimum dz (first level)?

If so, why are we increasing the dz here? In the end, we probably want 50m near the surface, and coarsening above. I don't see why we have to coarsen the grid.

2022-01-12 02:32 UTC, ilopezgp commented on driver/generate_namelist.jl
> +    namelist["grid"]["dz"] = 60.0
Same here and in others.

2022-01-12 02:32 UTC, ilopezgp commented on driver/generate_namelist.jl
> +    namelist_defaults["grid"]["stretch"] = true
I assume this is for testing this PR, but we will change it to False  before merging?

2022-01-12 02:34 UTC, ilopezgp commented
In general, I would prefer the stretching to be set to False by default for now, it makes calibration simpler. I mention this because I see that the mse tables have been updated to the stretched formulation.

2022-01-12 06:32 UTC, yairchn commented
> In general, I would prefer the stretching to be set to False by default for now, it makes calibration simpler. I mention this because I see that the mse tables have been updated to the stretched formulation.

First, Tapio prefers to have stretching as default - but that would be with the new stretching that is still in PR355 in CC. I could set it as false now but just heads up it will not stay this way.

The other issue is that if I set it to default now we will not be testing it ...

2022-02-24 23:49 UTC, charleskawczynski commented on driver/callbacks.jl
> +        # end
We're going to uncomment these, correct?

2022-02-24 23:51 UTC, charleskawczynski commented on driver/main.jl
> +    if stretched_grid
Should we maybe call this `truncated_gcm_mesh` or something? This is different from, and maybe somewhat unintuitive compared to, using a simple exponential stretching.

2022-03-25 22:55 UTC, trontrytel approved these changes
LGTM

Is there any link to ClimaCore docs you could add somewhere to explain how the mesh is constructed? I'm guessing that not all combinations of `nz`, `dz_surf`, `dz_toa` and `z_toa` 
are valid?

```
    namelist_defaults["grid"]["stretch"]["nz"] = 55
    namelist_defaults["grid"]["stretch"]["dz_surf"] = 30.0
    namelist_defaults["grid"]["stretch"]["dz_toa"] = 8000.0
    namelist_defaults["grid"]["stretch"]["z_toa"] = 45000.0
```

2022-03-26 15:02 UTC, charleskawczynski commented on .buildkite/pipeline.yml
> +        artifact_paths: "Output.Bomex.01_stretch_grid/stats/comparison/*"
```suggestion
        artifact_paths: "Output.Bomex.01_stretch_grid_true/stats/comparison/*"
```

2022-03-26 15:02 UTC, charleskawczynski commented on .buildkite/pipeline.yml
> +        artifact_paths: "Output.Bomex.01_stretch_grid/stats/comparison/*"
I think this should make the plots appear

2022-03-28 08:09 UTC, yairchn commented
Bors r+

2022-03-28 23:00 UTC, ilopezgp commented
> LGTM
> 
> Is there any link to ClimaCore docs you could add somewhere to explain how the mesh is constructed? I'm guessing that not all combinations of `nz`, `dz_surf`, `dz_toa` and `z_toa` are valid?
> 
> ```
>     namelist_defaults["grid"]["stretch"]["nz"] = 55
>     namelist_defaults["grid"]["stretch"]["dz_surf"] = 30.0
>     namelist_defaults["grid"]["stretch"]["dz_toa"] = 8000.0
>     namelist_defaults["grid"]["stretch"]["z_toa"] = 45000.0
> ```

+1 to this. Is this the resolution we aim for in the GCM?

Can we include as a comment above other combinations that could work? (e.g., coarser resolution for ensemble simulations, operational resolution for single simulations, high resolution for subseasonal NWP). These things WILL come up in the papers we want to write.

2022-03-28 23:04 UTC, ilopezgp approved these changes

2022-03-28 23:04 UTC, ilopezgp commented on integration_tests/driver.jl
> +        "--stretch_grid"   # Test stratched grid option
```suggestion
        "--stretch_grid"   # Test stretched grid option
```

2022-03-28 23:13 UTC, yairchn commented
Bors r+

2022-03-28 23:15 UTC, costachris approved these changes

2022-03-28 23:43 UTC, yairchn commented
Bors r+

2022-03-29 00:17 UTC, merged